language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install --upgrade tox-travis
  - pip install codecov

script:
  - tox -- --verbose

after_success:
  - codecov
